User.create(name: "Jackson", battlecry: "EERRUGGHH!!!!!")
User.create(name: "Dan", battlecry: "PAPA BLESS!")

Item.create(name: "Bam Bam's lucky Club", blk: 0, atk: 1, hp: 0, luck: 2, currency: 2)
Item.create(name: "Handaxe", blk: 0, atk: 1.5, hp: 0, luck: 0, currency: 1)
Item.create(name: "Iron Mace", blk: 0, atk: 2, hp: 0, luck: 1, currency: 3)
Item.create(name: "Iron Broadsword", blk: 1.5, atk: 2.5, hp: 0, luck: 0, currency: 3)
Item.create(name: "Guilded Dagger", blk: 0, atk: 1.5, hp: 0, luck: 3, currency: 5)
Item.create(name: "Spiked Brass Knuckles", blk: 0, atk: 3, hp: 0, luck: 0, currency: 3)

Item.create(name: "Leather Tunic", blk: 2, atk: 0, hp: 3, luck: 0, currency: 3)
Item.create(name: "Leather Coif", blk: 1, atk: 0, hp: 1, luck: 0, currency: 1)
Item.create(name: "Studded Chaps", blk: 2.5, atk: 0, hp: 1.5, luck: 0, currency: 3)
Item.create(name: "Blessed underwear", blk: 3, atk: 3, hp: 1, luck: 0, currency: 5)
Item.create(name: "Lucky Socks", blk: 0, atk: 0, hp: 0, luck: 6, currency: 5)

Item.create(name: "Sturdy Wooden Shield", blk: 2, atk: 0, hp: 0, luck: 0, currency: 1)
Item.create(name: "Spiked Buckler", blk: 3, atk: 1, hp: 1, luck: 0, currency: 4)
Item.create(name: "Flimsy Iron Shield", blk: 3, atk: 0, hp: 1, luck: 0, currency: 3)
Item.create(name: "Lucky Arm Guards", blk: 2, atk: 0, hp: 0, luck: 4, currency: 4)
Item.create(name: "Frozen Papa Johns Pizza", blk: 4, atk: 1, hp: 2, luck: 0, currency: 5)
